In [4]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [19]:
import tensorflow as tf

# Create a 3x3 matrix of ones
ones_matrix = tf.constant([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

# Create a 3x3 matrix of zeros
zeros_matrix = tf.constant([[0, 0, 0], [0, 0, 0], [0, 0, 0]])



In [21]:
# Add the two matrices together
result_matrix = tf.add(ones_matrix, zeros_matrix)

print(result_matrix)

tf.Tensor(
[[1 1 1]
 [1 1 1]
 [1 1 1]], shape=(3, 3), dtype=int32)
