In [3]:
import numpy as np
# for-in loop
#1d array
array_1D = np.array([1,2,3,4,5,6])
#iterate the elements in this array
print("array_1D :",array_1D)

for elements in array_1D:
    print(elements)


array_1D : [1 2 3 4 5 6]
1
2
3
4
5
6


In [5]:
array_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array :", array_2D)


2D array : [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#iterate 2D array
for elements in array_2D:
    print(elements)

[1 2 3]
[4 5 6]
[7 8 9]


In [11]:
#iterate 2D array each elements
for rows in array_2D:
    print(rows)
    for elements in rows:
        print(elements)

[1 2 3]
1
2
3
[4 5 6]
4
5
6
[7 8 9]
7
8
9


In [13]:
for elements in np.nditer(array_2D):
    print(elements)

1
2
3
4
5
6
7
8
9


In [21]:
#iterate the elements with index
for index, element in np.ndenumerate(array_2D):
      print(f"index:{index},Element: {element}")

index:(0, 0),Element: 1
index:(0, 1),Element: 2
index:(0, 2),Element: 3
index:(1, 0),Element: 4
index:(1, 1),Element: 5
index:(1, 2),Element: 6
index:(2, 0),Element: 7
index:(2, 1),Element: 8
index:(2, 2),Element: 9
