In [11]:
import numpy as np

array1 =np.array([1,2,3])
array2 =np.array([4,5,6])

#join array
concat_array = np.concatenate((array1,array2))
print(concat_array)

[1 2 3 4 5 6]


In [25]:
#create a multi diementional 

array2D_1 = np.array([[1,2,3],[4,5,6]])
array2D_2 = np.array([[7,8,9],[10,11,12]])

In [33]:
#vertically and horizontaally
#vstack - for vertical joining
#hstck - for horizontal

#verical using vstack
vstack_array = np.vstack((array2D_1,array2D_2))
print("vertical stacked array is :",vstack_array)

vertical stacked array is : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [35]:
#horizontal using hstack
hstack_array = np.hstack((array2D_1,array2D_2))
print(hstack_array)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
