In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

#create an array with 1dimentional
array_1D = np.array([1,2,3,4,5])
print("1D array is :",array_1D)

1D array is : [1 2 3 4 5]


In [5]:
#create 2d array
array_2D = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2D)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
array_3D = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(array_3D)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [15]:
#create an array with ones
array_ones = np.ones((2,4))
print(array_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
#array with zeros
array_zeros =np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
#create an array with perticular range
array_range =np.arange(10)
print(array_range)

[0 1 2 3 4 5 6 7 8 9]
